import { CNCBlock, CNCProgram, ControllerFormat, ConversionOptions } from "./types";

/**
 * Generate Siemens 840d code from a parsed program
 */
export function generateSiemens840d(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`%_N_${program.programName || "PROGRAM"}_MPF`);
      lines.push(`;${options?.commentStyle === "parens" ? "(" : ""} Generated by CNC Converter${options?.commentStyle === "parens" ? ")" : ""}`);
      continue;
    }

    if (block.isProgramEnd) {
      lines.push(block.mCodes.length ? block.mCodes[0] : "M02");
      lines.push("%");
      continue;
    }

    // Build addresses from parsed data
    for (const g of block.gCodes) {
      line += g + " ";
    }

    // Add axes
    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}=${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) {
      line += `F=${formatNumber(block.feed, 2)} `;
    }

    if (block.spindleSpeed !== undefined) {
      line += `S=${Math.round(block.spindleSpeed)} `;
    }

    if (block.toolNumber !== undefined) {
      line += `T${block.toolNumber} `;
    }
    if (block.toolName !== undefined) {
      line += `T="${block.toolName}" `;
    }

    // Siemens cycles
    if (block.siemensCycleCall) {
      line = block.siemensCycleCall + " ";
    }

    for (const m of block.mCodes) {
      line += m + " ";
    }

    // Add other addresses
    for (const [addr, val] of Object.entries(block.addresses)) {
      if (!["G", "M", "X", "Y", "Z", "A", "B", "C", "F", "S", "T", "I", "J", "K", "R", "D", "H", "P", "Q", "CALL"].includes(addr)) {
        line += `${addr}${typeof val === "number" ? formatNumber(val) : val} `;
      }
    }

    line = line.trim();

    if (block.comment) {
      line += line ? ` ;${block.comment}` : `;${block.comment}`;
    }

    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Siemens 828D — identical to 840D in generation
 */
export function generateSiemens828d(program: CNCProgram, options?: ConversionOptions): string {
  return generateSiemens840d(program, options);
}

/**
 * Generate standard Fanuc-style G-code (used by Fanuc 0i, 31i, Haas, Brother)
 */
export function generateFanucStyle(
  program: CNCProgram,
  options?: ConversionOptions,
  format: ControllerFormat = "fanuc-0i",
): string {
  const lines: string[] = [];
  const progNum = options?.programNumber || 1;
  const useDecimal = format === "haas"; // Haas uses decimal format

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`O${String(progNum).padStart(4, "0")}`);
      const commentChar = options?.commentStyle === "semicolon" ? ";" : "(";
      lines.push(`${commentChar}Generated by CNC Converter${commentChar === "(" ? ")" : ""}`);
      continue;
    }

    if (block.isProgramEnd) {
      lines.push(block.mCodes.length ? block.mCodes[0] : "M02");
      lines.push("%");
      continue;
    }

    // Heidenhain commands → Fanuc conversion
    if (block.heidenhainCommand === "L") {
      line = "G01 ";
      for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
        if (block.axes[axis] !== undefined) {
          const val = block.axes[axis];
          line += `${axis}${useDecimal ? val.toFixed(2) : formatNumber(val)} `;
        }
      }
      if (block.feed) line += `F${formatNumber(block.feed, 2)} `;
      for (const m of block.mCodes) line += m + " ";
      lines.push(line.trim());
      continue;
    }

    if (block.heidenhainCommand === "TOOL CALL" && block.toolNumber) {
      line = `T${String(block.toolNumber).padStart(2, "0")} M6` + (block.spindleSpeed ? ` S${Math.round(block.spindleSpeed)}` : "");
      lines.push(line);
      continue;
    }

    if (block.heidenhainCommand === "CYCL DEF") {
      // Heidenhain cycles → G81-G89 where possible
      const cycleNum = parseFloat(block.cycle || "0");
      if (cycleNum >= 200 && cycleNum <= 212) {
        // Drilling cycles
        const gMap: Record<number, string> = {
          200: "G81", 201: "G82", 202: "G83", 203: "G84",
          204: "G85", 205: "G86", 206: "G87", 207: "G88", 208: "G89",
        };
        line = gMap[cycleNum] || `(CYCL DEF ${cycleNum})`;
        lines.push(line);
      } else {
        lines.push(`(CYCL DEF ${cycleNum})`);
      }
      continue;
    }

    if (block.heidenhainCommand === "CYCL CALL") {
      lines.push("G80");
      continue;
    }

    // Siemens cycle calls → standard G-code
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToFanuc(block, format);
      if (block.comment) line += ` (${block.comment})`;
      lines.push(line);
      continue;
    }

    // Build addresses
    for (const g of block.gCodes) {
      const gNum = parseInt(g.replace("G", ""), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    // Add axes
    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        const val = block.axes[axis];
        line += `${axis}${formatNumber(val)} `;
      }
    }

    // I, J, K for arcs
    if (block.addresses["I"] !== undefined) line += `I${formatNumber(block.addresses["I"] as number)} `;
    if (block.addresses["J"] !== undefined) line += `J${formatNumber(block.addresses["J"] as number)} `;
    if (block.addresses["K"] !== undefined) line += `K${formatNumber(block.addresses["K"] as number)} `;

    if (block.feed !== undefined) {
      line += `F${formatNumber(block.feed, 2)} `;
    }

    if (block.spindleSpeed !== undefined) {
      line += `S${Math.round(block.spindleSpeed)} `;
    }

    // Tool call
    if (block.toolNumber !== undefined) {
      line += `T${String(block.toolNumber).padStart(2, "0")} `;
    }

    // R plane for cycles, Q for peck, etc
    if (block.addresses["R"] !== undefined) line += `R${formatNumber(block.addresses["R"] as number)} `;
    if (block.addresses["Q"] !== undefined) line += `Q${formatNumber(block.addresses["Q"] as number)} `;
    if (block.addresses["D"] !== undefined) line += `D${formatNumber(block.addresses["D"] as number)} `;
    if (block.addresses["H"] !== undefined) line += `H${formatNumber(block.addresses["H"] as number)} `;
    if (block.addresses["P"] !== undefined) line += `P${formatNumber(block.addresses["P"] as number)} `;

    for (const m of block.mCodes) {
      line += m + " ";
    }

    // Add other addresses
    for (const [addr, val] of Object.entries(block.addresses)) {
      if (!["G", "M", "X", "Y", "Z", "A", "B", "C", "F", "S", "T", "I", "J", "K", "R", "D", "H", "P", "Q"].includes(addr)) {
        line += `${addr}${typeof val === "number" ? formatNumber(val) : val} `;
      }
    }

    line = line.trim();

    if (block.comment) {
      line += line ? ` (${block.comment})` : `(${block.comment})`;
    }

    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Generate Mitsubishi M80 code
 */
export function generateMitsubishiM80(program: CNCProgram, options?: ConversionOptions): string {
  return generateFanucStyle(program, options, "mitsubishi-m80");
}

/**
 * Generate Mitsubishi M70 code
 */
export function generateMitsubishiM70(program: CNCProgram, options?: ConversionOptions): string {
  return generateFanucStyle(program, options, "mitsubishi-m70");
}

/**
 * Generate Haas code (Fanuc-style with decimal points)
 */
export function generateHaas(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];
  const progNum = options?.programNumber || 1;

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`O${String(progNum).padStart(4, "0")}`);
      lines.push(`(Generated by CNC Converter)`);
      continue;
    }

    if (block.isProgramEnd) {
      if (block.mCodes.length) {
        // Haas uses M30 for program end
        lines.push(block.mCodes.includes("M30") ? "M30" : block.mCodes[0]);
      } else {
        lines.push("M30");
      }
      lines.push("%");
      continue;
    }

    // Siemens cycles → Haas
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToFanuc(block, "haas");
      if (block.comment) line += ` (${block.comment})`;
      lines.push(line);
      continue;
    }

    // Heidenhain → Haas
    if (block.heidenhainCommand === "L") {
      line = "G01 ";
      for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
        if (block.axes[axis] !== undefined) {
          line += `${axis}${block.axes[axis].toFixed(3)} `;
        }
      }
      if (block.feed) line += `F${block.feed.toFixed(2)} `;
      for (const m of block.mCodes) line += m + " ";
      lines.push(line.trim());
      continue;
    }

    if (block.heidenhainCommand === "TOOL CALL" && block.toolNumber) {
      line = `T${String(block.toolNumber).padStart(2, "0")} M6` + (block.spindleSpeed ? ` S${Math.round(block.spindleSpeed)}` : "");
      lines.push(line);
      continue;
    }

    // Build standard addresses
    for (const g of block.gCodes) {
      const gNum = parseInt(g.replace("G", ""), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}${block.axes[axis].toFixed(3)} `;
      }
    }

    if (block.addresses["I"] !== undefined) line += `I${formatNumber(block.addresses["I"] as number)} `;
    if (block.addresses["J"] !== undefined) line += `J${formatNumber(block.addresses["J"] as number)} `;
    if (block.addresses["K"] !== undefined) line += `K${formatNumber(block.addresses["K"] as number)} `;

    if (block.feed !== undefined) line += `F${formatNumber(block.feed, 2)} `;
    if (block.spindleSpeed !== undefined) line += `S${Math.round(block.spindleSpeed)} `;
    if (block.toolNumber !== undefined) line += `T${String(block.toolNumber).padStart(2, "0")} `;
    if (block.addresses["R"] !== undefined) line += `R${formatNumber(block.addresses["R"] as number)} `;
    if (block.addresses["Q"] !== undefined) line += `Q${formatNumber(block.addresses["Q"] as number)} `;

    for (const m of block.mCodes) line += m + " ";

    line = line.trim();
    if (block.comment) line += line ? ` (${block.comment})` : `(${block.comment})`;
    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Generate Brother Speedio code (Fanuc-style with Brother-specific)
 */
export function generateBrotherSpeedio(program: CNCProgram, options?: ConversionOptions): string {
  return generateFanucStyle(program, options, "brother-speedio");
}

/**
 * Generate Heidenhain TNC 640 code
 */
export function generateHeidenhainTNC640(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`BEGIN PGM ${program.programName || "PROGRAM"} MM`);
      lines.push(`;Generated by CNC Converter`);
      continue;
    }

    if (block.isProgramEnd) {
      lines.push(`END PGM ${program.programName || "PROGRAM"} MM`);
      continue;
    }

    if (block.heidenhainCommand) {
      if (block.heidenhainCommand === "L") {
        line = "L ";
        for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
          if (block.axes[axis] !== undefined) {
            const val = block.axes[axis];
            line += `${axis}${val >= 0 ? "+" : ""}${formatNumber(val)} `;
          }
        }
        if (block.feed) line += `F${Math.round(block.feed)} `;
        if (block.spindleSpeed) line += `S${Math.round(block.spindleSpeed)} `;
        for (const m of block.mCodes) line += m + " ";
        lines.push(line.trim());
        continue;
      }

      if (block.heidenhainCommand === "TOOL CALL") {
        line = `TOOL CALL ${block.toolNumber || 1} Z S${Math.round(block.spindleSpeed || 5000)}`;
        lines.push(line);
        continue;
      }

      if (block.heidenhainCommand === "CYCL DEF") {
        const operation = block.mCodes[0] || "DRILLING";
        line = `CYCL DEF ${block.cycle || "200"} ${operation}`;
        lines.push(line);
        continue;
      }

      if (block.heidenhainCommand === "CYCL CALL") {
        lines.push("CYCL CALL");
        continue;
      }

      if (block.heidenhainCommand === "BEGIN") {
        lines.push(`BEGIN PGM ${program.programName || "PROGRAM"} MM`);
        continue;
      }

      if (block.heidenhainCommand === "END") {
        lines.push(`END PGM ${program.programName || "PROGRAM"} MM`);
        continue;
      }

      if (block.heidenhainCommand === "LBL") {
        lines.push(block.raw);
        continue;
      }

      if (["CC", "CP", "CR", "CT", "APPR", "DEP", "RND", "CHF", "MIRROR", "ROT", "SCALE", "TRAFO", "BLK FORM", "FN0", "FN1", "FN2", "Q"].includes(block.heidenhainCommand)) {
        lines.push(block.raw);
        continue;
      }
    }

    // Standard G-code to Heidenhain conversion
    if (block.gCodes.length > 0) {
      // Convert G0/G1 to L moves
      const gNum = parseInt(block.gCodes[0].replace("G", ""), 10);
      if (!isNaN(gNum) && (gNum === 0 || gNum === 1)) {
        line = "L ";
        for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
          if (block.axes[axis] !== undefined) {
            line += `${axis}${block.axes[axis] >= 0 ? "+" : ""}${formatNumber(block.axes[axis])} `;
          }
        }
        if (gNum === 0) line += "R0 ";
        if (block.feed) line += `F${Math.round(block.feed)} `;
        if (block.spindleSpeed) line += `S${Math.round(block.spindleSpeed)} `;
        for (const m of block.mCodes) line += m + " ";

        // Cycle detection from G-codes
        if (gNum >= 81 && gNum <= 89) {
          const heidenhainCycles: Record<number, string> = {
            81: "CYCL DEF 200 DRILLING", 82: "CYCL DEF 201 DWELLING",
            83: "CYCL DEF 202 PECKING", 84: "CYCL DEF 203 TAPPING",
          };
          lines.push(heidenhainCycles[gNum] || `CYCL DEF 200 DRILLING`);
          if (block.axes["Z"] !== undefined) {
            // Add Q parameters for the cycle
            lines.push(`QL200=${block.addresses["R"] || 2}; SET-UP`);
            lines.push(`QL201=${-(Math.abs(block.axes["Z"]))}; DEPTH`);
            lines.push(`QL202=2; FEED`);
          }
          lines.push("CYCL CALL");
          continue;
        }

        lines.push(line.trim());
        continue;
      }

      // G02/G03 → CR/CP
      if (!isNaN(gNum) && (gNum === 2 || gNum === 3)) {
        const dir = gNum === 2 ? "DR-" : "DR+";
        line = "CR ";
        for (const axis of ["X", "Y", "Z"]) {
          if (block.axes[axis] !== undefined) {
            line += `${axis}${block.axes[axis] >= 0 ? "+" : ""}${formatNumber(block.axes[axis])} `;
          }
        }
        if (block.addresses["I"] !== undefined && block.addresses["J"] !== undefined) {
          const iVal = block.addresses["I"] as number;
          const jVal = block.addresses["J"] as number;
          const r = Math.sqrt(iVal * iVal + jVal * jVal);
          line += `${dir} R+${formatNumber(r)} `;
        }
        if (block.feed) line += `F${Math.round(block.feed)} `;
        lines.push(line.trim());
        continue;
      }
    }

    // Tool change
    if (block.toolNumber !== undefined && !block.heidenhainCommand) {
      line = `TOOL CALL ${block.toolNumber} Z S${Math.round(block.spindleSpeed || 5000)}`;
      lines.push(line);
      continue;
    }

    // Standalone M codes
    if (block.mCodes.length > 0 && !block.heidenhainCommand) {
      lines.push(block.mCodes[0]);
      continue;
    }

    // Comment only
    if (block.comment) {
      lines.push(`;${block.comment}`);
      continue;
    }
  }

  return lines.join("\n");
}

/**
 * Heidenhain iTNC 530 — similar to TNC 640
 */
export function generateHeidenhainITNC530(program: CNCProgram, options?: ConversionOptions): string {
  return generateHeidenhainTNC640(program, options);
}

/**
 * Generate Okuma OSP code
 */
export function generateOkumaOSP(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];
  const progNum = options?.programNumber || 1;

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`O${String(progNum).padStart(4, "0")}`);
      lines.push(`(Generated by CNC Converter)`);
      continue;
    }

    if (block.isProgramEnd) {
      if (block.mCodes.includes("M02") || block.mCodes.includes("M30")) {
        lines.push(block.mCodes.find(m => m === "M02" || m === "M30") || "M02");
      } else {
        lines.push("M02");
      }
      continue;
    }

    // Siemens cycles → Okuma
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToG81(block);
      if (block.comment) line += ` (${block.comment})`;
      lines.push(line);
      continue;
    }

    // Build standard format
    for (const g of block.gCodes) {
      const gNum = parseInt(g.replace("G", ""), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) line += `F${formatNumber(block.feed, 2)} `;
    if (block.spindleSpeed !== undefined) line += `S${Math.round(block.spindleSpeed)} `;
    if (block.toolNumber !== undefined) line += `T${String(block.toolNumber).padStart(2, "0")} `;

    for (const m of block.mCodes) line += m + " ";

    line = line.trim();
    if (block.comment) line += line ? ` (${block.comment})` : `(${block.comment})`;
    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Generate Mazak Mazatrol code
 */
export function generateMazakMazatrol(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`{UNIT SYSTEM METRIC}`);
      lines.push(`(Generated by CNC Converter)`);
      continue;
    }

    if (block.isProgramEnd) {
      if (block.mCodes.length) {
        lines.push(block.mCodes.includes("M30") ? "M30" : block.mCodes[0]);
      } else {
        lines.push("M30");
      }
      continue;
    }

    // Mazatrol section header
    if (block.addresses["section"]) {
      lines.push(block.addresses["section"] as string);
      continue;
    }

    // Siemens cycles → Mazatrol fixed cycles
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToG81(block);
      if (block.comment) line += ` (${block.comment})`;
      lines.push(line);
      continue;
    }

    // G-code line
    for (const g of block.gCodes) {
      const gNum = parseInt(g.replace("G", ""), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    for (const axis of ["X", "Y", "Z"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) line += `F${formatNumber(block.feed, 2)} `;
    if (block.spindleSpeed !== undefined) line += `S${Math.round(block.spindleSpeed)} `;
    if (block.toolNumber !== undefined) line += `T${String(block.toolNumber).padStart(2, "0")} `;

    for (const m of block.mCodes) line += m + " ";

    line = line.trim();
    if (block.comment) line += line ? ` (${block.comment})` : `(${block.comment})`;
    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Mazak Smooth — similar to Mazatrol
 */
export function generateMazakSmooth(program: CNCProgram, options?: ConversionOptions): string {
  return generateMazakMazatrol(program, options);
}

/**
 * Generate Fagor 8055 code
 */
export function generateFagor8055(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];
  const progNum = options?.programNumber || 1;

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`(PROGRAM O${String(progNum).padStart(4, "0")})`);
      lines.push(`(Generated by CNC Converter)`);
      continue;
    }

    if (block.isProgramEnd) {
      if (block.mCodes.includes("M30")) {
        lines.push("M30");
      } else {
        lines.push("M02");
      }
      continue;
    }

    // Siemens cycles → Fagor
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToG81(block);
      if (block.comment) line += ` (${block.comment})`;
      lines.push(line);
      continue;
    }

    // Fagor conversational
    if (block.addresses["fagor-op"]) {
      lines.push(block.addresses["fagor-op"] as string);
      continue;
    }

    // Standard G-code
    for (const g of block.gCodes) {
      const gNum = parseInt(g.replace("G", ""), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) line += `F${formatNumber(block.feed, 2)} `;
    if (block.spindleSpeed !== undefined) line += `S${Math.round(block.spindleSpeed)} `;
    if (block.toolNumber !== undefined) line += `T${String(block.toolNumber).padStart(2, "0")} `;

    for (const m of block.mCodes) line += m + " ";

    line = line.trim();
    if (block.comment) line += line ? ` (${block.comment})` : `(${block.comment})`;
    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Generate Bosch MTX code
 */
export function generateBoschMTX(program: CNCProgram, options?: ConversionOptions): string {
  return generateSiemens840d(program, options);
}

/**
 * Convert Siemens cycle call to Fanuc-style fixed cycle
 */
function convertSiemensCycleToFanuc(block: CNCBlock, format: ControllerFormat): string {
  const cycle = block.cycle?.toUpperCase();
  const params = block.cycleParams;
  let line = "";

  switch (cycle) {
    case "CYCLE81": {
      const rfp = params[1] || 0;
      const sdip = params[2] || 0;
      const dp = params[3] || 0;
      const ret = rfp + sdip;
      line = `G81 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${block.feed || 100}`;
      break;
    }
    case "CYCLE83": {
      const rfp = params[1] || 0;
      const dp = params[3] || 0;
      const fdep = params[5] || dp / 2;
      const dam = params[7] || 3;
      const ret = rfp + (params[2] || 0);
      line = `G83 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} Q${formatNumber(fdep > 0 ? fdep : Math.min(dam, dp / 4))} F${block.feed || 80}`;
      break;
    }
    case "CYCLE84": {
      const dp = params[3] || 0;
      const rfp = params[1] || 0;
      const pitch = params[8] || 1.5;
      const ret = rfp + (params[2] || 0);
      const sst = params[10] || block.spindleSpeed || 500;
      line = `G84 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${formatNumber(sst * pitch, 2)} S${Math.round(sst)}`;
      break;
    }
    case "CYCLE85": {
      const dp = params[3] || 0;
      const rfp = params[1] || 0;
      const ffr = params[6] || block.feed || 100;
      const ret = rfp + (params[2] || 0);
      line = `G85 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${formatNumber(ffr, 2)}`;
      break;
    }
    default:
      line = `(${block.siemensCycleCall})`;
      break;
  }

  return line;
}

/**
 * Convert Siemens cycle to G81 with depth (simple conversion)
 */
function convertSiemensCycleToG81(block: CNCBlock): string {
  const cycle = block.cycle?.toUpperCase();
  const params = block.cycleParams;
  let line = "";

  switch (cycle) {
    case "CYCLE81": {
      const dp = params[3] || 0;
      line = `G81 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(params[1] || 2)} F${block.feed || 100}`;
      break;
    }
    case "CYCLE83": {
      const dp = params[3] || 0;
      const dam = params[7] || 3;
      line = `G83 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(params[1] || 2)} Q${Math.min(dam, Math.abs(dp) / 4)} F${block.feed || 80}`;
      break;
    }
    case "CYCLE84": {
      const dp = params[3] || 0;
      const pitch = params[8] || 1.5;
      const sst = params[10] || block.spindleSpeed || 500;
      line = `G84 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(params[1] || 2)} F${formatNumber(sst * pitch, 2)} S${Math.round(sst)}`;
      break;
    }
    case "CYCLE85": {
      const dp = params[3] || 0;
      const ffr = params[6] || block.feed || 100;
      line = `G85 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(params[1] || 2)} F${formatNumber(ffr, 2)}`;
      break;
    }
    default:
      line = `(${block.siemensCycleCall})`;
      break;
  }

  return line;
}

function formatNumber(num: number, decimals?: number): string {
  const val = typeof num === "number" ? num : parseFloat(String(num));
  if (isNaN(val)) return "0";
  if (decimals !== undefined) {
    return val.toFixed(decimals);
  }
  return parseFloat(val.toFixed(4)).toString();
}

export function generateProgram(
  program: CNCProgram,
  format: ControllerFormat,
  options?: ConversionOptions,
): string {
  switch (format) {
    case "siemens-840d":
      return generateSiemens840d(program, options);
    case "siemens-828d":
      return generateSiemens828d(program, options);
    case "mitsubishi-m80":
      return generateMitsubishiM80(program, options);
    case "mitsubishi-m70":
      return generateMitsubishiM70(program, options);
    case "fanuc-0i":
    case "fanuc-31i":
      return generateFanucStyle(program, options, format);
    case "heidenhain-tnc640":
      return generateHeidenhainTNC640(program, options);
    case "heidenhain-itnc530":
      return generateHeidenhainITNC530(program, options);
    case "mazak-mazatrol":
      return generateMazakMazatrol(program, options);
    case "mazak-smooth":
      return generateMazakSmooth(program, options);
    case "okuma-osp":
      return generateOkumaOSP(program, options);
    case "haas":
      return generateHaas(program, options);
    case "brother-speedio":
      return generateBrotherSpeedio(program, options);
    case "fagor-8055":
      return generateFagor8055(program, options);
    case "bosch-mtx":
      return generateBoschMTX(program, options);
    default:
      return generateFanucStyle(program, options, "fanuc-0i");
  }
}
