import { CNCBlock, CNCProgram, ControllerFormat, ConversionOptions } from "./types";

/**
 * Generate Siemens 840d code from a parsed program
 */
export function generateSiemens840d(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`%_N_${program.programName || "PROGRAM"}_MPF`);
      lines.push(`;${options?.commentStyle === "parens" ? "(" : ""} Generated by CNC Converter${options?.commentStyle === "parens" ? ")" : ""}`);
      continue;
    }

    if (block.isProgramEnd) {
      lines.push(block.mCodes.length ? block.mCodes[0] : "M02");
      lines.push("%");
      continue;
    }

    // Build addresses from parsed data
    for (const g of block.gCodes) {
      line += g + " ";
    }

    // Add axes
    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}=${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) {
      line += `F=${formatNumber(block.feed, 2)} `;
    }

    if (block.spindleSpeed !== undefined) {
      line += `S=${Math.round(block.spindleSpeed)} `;
    }

    if (block.toolNumber !== undefined) {
      line += `T${block.toolNumber} `;
    }
    if (block.toolName !== undefined) {
      line += `T="${block.toolName}" `;
    }

    // Siemens cycles
    if (block.siemensCycleCall) {
      line = block.siemensCycleCall + " ";
    }

    for (const m of block.mCodes) {
      line += m + " ";
    }

    // Add other addresses
    for (const [addr, val] of Object.entries(block.addresses)) {
      if (!["G", "M", "X", "Y", "Z", "A", "B", "C", "F", "S", "T"].includes(addr)) {
        line += `${addr}${typeof val === "number" ? formatNumber(val) : val} `;
      }
    }

    line = line.trim();

    if (block.comment) {
      line += line ? ` ;${block.comment}` : `;${block.comment}`;
    }

    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Generate Mitsubishi M80 code from a parsed program
 */
export function generateMitsubishiM80(program: CNCProgram, options?: ConversionOptions): string {
  const lines: string[] = [];
  const progNum = options?.programNumber || 1;

  for (let i = 0; i < program.blocks.length; i++) {
    const block = program.blocks[i];
    let line = "";

    if (block.isProgramStart) {
      lines.push(`O${String(progNum).padStart(4, "0")}`);
      lines.push(options?.commentStyle === "semicolon" ? `; Generated by CNC Converter` : `(Generated by CNC Converter)`);
      continue;
    }

    if (block.isProgramEnd) {
      lines.push(block.mCodes.length ? block.mCodes[0] : "M02");
      lines.push("%");
      continue;
    }

    // Convert Siemens cycles to fixed cycles
    if (block.siemensCycleCall) {
      line = convertSiemensCycleToMitsubishi(block);
      if (block.comment) {
        line += ` (${block.comment})`;
      }
      lines.push(line);
      continue;
    }

    // Build addresses
    for (const g of block.gCodes) {
      // Convert Siemens G-codes to Mitsubishi (pad to 2 digits)
      const gNum = parseInt(g.slice(1), 10);
      if (!isNaN(gNum)) {
        line += `G${String(gNum).padStart(2, "0")} `;
      } else {
        line += g + " ";
      }
    }

    // Add axes (no = sign in Mitsubishi)
    for (const axis of ["X", "Y", "Z", "A", "B", "C"]) {
      if (block.axes[axis] !== undefined) {
        line += `${axis}${formatNumber(block.axes[axis])} `;
      }
    }

    if (block.feed !== undefined) {
      line += `F${formatNumber(block.feed, 2)} `;
    }

    if (block.spindleSpeed !== undefined) {
      line += `S${Math.round(block.spindleSpeed)} `;
    }

    // Tool call in Mitsubishi: Txx M6
    if (block.toolNumber !== undefined) {
      line += `T${String(block.toolNumber).padStart(2, "0")} `;
      if (block.mCodes.length === 0 || !block.mCodes.some((m) => m === "M6")) {
        // Don't add M6 automatically, only if it was in the block
      }
    }

    for (const m of block.mCodes) {
      line += m + " ";
    }

    // Add other addresses
    for (const [addr, val] of Object.entries(block.addresses)) {
      if (!["G", "M", "X", "Y", "Z", "A", "B", "C", "F", "S", "T"].includes(addr)) {
        line += `${addr}${typeof val === "number" ? formatNumber(val) : val} `;
      }
    }

    line = line.trim();

    if (block.comment) {
      line += line ? ` (${block.comment})` : `(${block.comment})`;
    }

    lines.push(line || "");
  }

  return lines.join("\n");
}

/**
 * Convert Siemens cycle call to Mitsubishi fixed cycle
 */
function convertSiemensCycleToMitsubishi(block: CNCBlock): string {
  const cycle = block.cycle?.toUpperCase();
  const params = block.cycleParams;
  let line = "";

  switch (cycle) {
    case "CYCLE81": {
      // CYCLE81(RTP, RFP, SDIS, DP, DPR) → G81
      const rfp = params[1] || 0; // Reference plane
      const sdip = params[2] || 0; // Safety distance
      const dp = params[3] || 0; // Final depth
      const ret = rfp + sdip; // Retract plane
      line = `G81 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${block.feed || 100}`;
      break;
    }
    case "CYCLE83": {
      // CYCLE83(RTP, RFP, SDIS, DP, DPR, FDEP, FDPR, DAM, DTB, DTS, FRF, VARI)
      const rfp = params[1] || 0;
      const dp = params[3] || 0;
      const fdep = params[5] || dp / 2; // First drilling depth
      const dam = params[7] || 3; // Degression amount
      const ret = rfp + (params[2] || 0);
      line = `G83 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} Q${formatNumber(fdep > 0 ? fdep : Math.min(dam, dp / 4))} F${block.feed || 80}`;
      break;
    }
    case "CYCLE84": {
      // CYCLE84(RTP, RFP, SDIS, DP, DPR, DTB, SDAC, MPIT, PIT, POSS, SST, SST1)
      const dp = params[3] || 0;
      const rfp = params[1] || 0;
      const pitch = params[8] || 1.5;
      const ret = rfp + (params[2] || 0);
      const sst = params[10] || block.spindleSpeed || 500;
      // G84 tapping
      line = `G84 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${formatNumber(sst * pitch, 2)} S${Math.round(sst)}`;
      break;
    }
    case "CYCLE85": {
      // CYCLE85(RTP, RFP, SDIS, DP, DPR, DTB, FFR, RFF)
      const dp = params[3] || 0;
      const rfp = params[1] || 0;
      const ffr = params[6] || block.feed || 100;
      const ret = rfp + (params[2] || 0);
      line = `G85 X${formatNumber(block.axes["X"] || 0)} Y${formatNumber(block.axes["Y"] || 0)} Z${formatNumber(-dp)} R${formatNumber(ret)} F${formatNumber(ffr, 2)}`;
      break;
    }
    default:
      // Unknown cycle, output as comment
      line = `(${block.siemensCycleCall})`;
      break;
  }

  return line;
}

function formatNumber(num: number, decimals?: number): string {
  if (decimals !== undefined) {
    return num.toFixed(decimals);
  }
  // Use 3 decimals by default, strip trailing zeros
  return parseFloat(num.toFixed(4)).toString();
}

export function generateProgram(program: CNCProgram, format: ControllerFormat, options?: ConversionOptions): string {
  switch (format) {
    case "siemens-840d":
      return generateSiemens840d(program, options);
    case "mitsubishi-m80":
      return generateMitsubishiM80(program, options);
  }
}
