import { InsertDefinition, InsertHolderDefinition, InsertShape, InsertClearance, InsertChipbreaker, InsertTolerance } from "./types";

/**
 * ISO 1832 Insert Database
 *
 * Covers all common insert shapes, sizes, geometries, and materials
 * used in turning, milling, threading, grooving, and parting operations.
 */

const INSERTS: InsertDefinition[] = [
  // ==========================================
  // CNMG — General Turning (80° Rhombic Negative)
  // ==========================================
  {
    id: "cnmg-120408-gp",
    isoCode: "CNMG 120408",
    shape: "C",
    clearance: "N",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 4.0 },
    recommendedFeed: { min: 0.08, max: 0.35 },
    maxDepthOfCut: 5.0,
    maxFeedRate: 0.5,
    notes: "Most common general turning insert. Works on steel, stainless, and cast iron.",
    brand: "Sandvik",
    series: "432R",
  },
  {
    id: "cnmg-120408-fi",
    isoCode: "CNMG 120408-FI",
    shape: "C",
    clearance: "N",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "coated-carbide",
    coating: "tin",
    isoApplicationGroup: "P05-P20",
    recommendedDOC: { min: 0.15, max: 2.0 },
    recommendedFeed: { min: 0.05, max: 0.2 },
    maxDepthOfCut: 2.5,
    maxFeedRate: 0.3,
    notes: "Finishing geometry for steel — excellent surface finish.",
    brand: "Sandvik",
    series: "432R-F",
  },
  {
    id: "cnmg-120408-ro",
    isoCode: "CNMG 120408-RO",
    shape: "C",
    clearance: "N",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "roughing",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P20-P40",
    recommendedDOC: { min: 1.0, max: 6.0 },
    recommendedFeed: { min: 0.15, max: 0.5 },
    maxDepthOfCut: 8.0,
    maxFeedRate: 0.7,
    notes: "Roughing geometry with reinforced cutting edge.",
    brand: "Sandvik",
    series: "432R-R",
  },
  {
    id: "cnmg-160608",
    isoCode: "CNMG 160608",
    shape: "C",
    clearance: "N",
    tolerance: "M",
    size: 16,
    thickness: 6.35,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 5.0 },
    recommendedFeed: { min: 0.1, max: 0.4 },
    maxDepthOfCut: 6.0,
    maxFeedRate: 0.6,
    notes: "Larger CNMG for heavier cuts. Common in automotive.",
    brand: "Seco",
    series: "TP250",
  },
  {
    id: "cnmg-120408-cbn",
    isoCode: "CNMG 120408 CBN",
    shape: "C",
    clearance: "N",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "cbn",
    coating: "uncoated",
    isoApplicationGroup: "H05-H15",
    recommendedDOC: { min: 0.05, max: 0.5 },
    recommendedFeed: { min: 0.02, max: 0.1 },
    maxDepthOfCut: 0.8,
    maxFeedRate: 0.15,
    notes: "CBN for hardened steel finishing (45-65 HRC). High speed, light cuts.",
    brand: "Sumitomo",
    series: "BN600",
  },

  // ==========================================
  // DCMT — 55° Diamond Positive (Finishing)
  // ==========================================
  {
    id: "dcmt-11t304",
    isoCode: "DCMT 11T304",
    shape: "D",
    clearance: "C",
    tolerance: "M",
    size: 11,
    thickness: 3.97,
    noseRadius: 0.4,
    chipbreaker: "finishing",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P20",
    recommendedDOC: { min: 0.1, max: 1.5 },
    recommendedFeed: { min: 0.03, max: 0.15 },
    maxDepthOfCut: 2.0,
    maxFeedRate: 0.2,
    notes: "Small positive rake insert. Excellent for small-diameter boring bars.",
    brand: "Iscar",
    series: "IC907",
  },
  {
    id: "dcmt-11t308",
    isoCode: "DCMT 11T308",
    shape: "D",
    clearance: "C",
    tolerance: "M",
    size: 11,
    thickness: 3.97,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P15-P30",
    recommendedDOC: { min: 0.2, max: 2.0 },
    recommendedFeed: { min: 0.05, max: 0.2 },
    maxDepthOfCut: 3.0,
    maxFeedRate: 0.3,
    notes: "Common in boring and light turning operations.",
    brand: "Iscar",
    series: "IC908",
  },

  // ==========================================
  // DNMG — 55° Diamond Negative
  // ==========================================
  {
    id: "dnmg-150408",
    isoCode: "DNMG 150408",
    shape: "D",
    clearance: "N",
    tolerance: "M",
    size: 15,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P15-P30",
    recommendedDOC: { min: 0.5, max: 4.0 },
    recommendedFeed: { min: 0.08, max: 0.3 },
    maxDepthOfCut: 5.0,
    maxFeedRate: 0.45,
    notes: "Negative rake 55° rhombus. Good for roughing and general turning.",
    brand: "Kyocera",
    series: "CA515",
  },

  // ==========================================
  // SNMG — Square Negative (General Turning)
  // ==========================================
  {
    id: "snmg-120408",
    isoCode: "SNMG 120408",
    shape: "S",
    clearance: "N",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 4.0 },
    recommendedFeed: { min: 0.1, max: 0.35 },
    maxDepthOfCut: 5.0,
    maxFeedRate: 0.5,
    notes: "90° approach angle. Can turn and face.",
    brand: "Kennametal",
    series: "KC5010",
  },
  {
    id: "snmg-190612",
    isoCode: "SNMG 190612",
    shape: "S",
    clearance: "N",
    tolerance: "M",
    size: 19,
    thickness: 6.35,
    noseRadius: 1.2,
    chipbreaker: "roughing",
    material: "coated-carbide",
    coating: "altin",
    isoApplicationGroup: "P25-P45",
    recommendedDOC: { min: 1.0, max: 7.0 },
    recommendedFeed: { min: 0.15, max: 0.5 },
    maxDepthOfCut: 10.0,
    maxFeedRate: 0.8,
    notes: "Heavy roughing square insert. High material removal rates.",
    brand: "Kennametal",
    series: "KCU25",
  },

  // ==========================================
  // TNMG — Triangular Negative
  // ==========================================
  {
    id: "tnmg-160408",
    isoCode: "TNMG 160408",
    shape: "T",
    clearance: "N",
    tolerance: "M",
    size: 16,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 4.0 },
    recommendedFeed: { min: 0.08, max: 0.3 },
    maxDepthOfCut: 5.0,
    maxFeedRate: 0.45,
    notes: "Three cutting edges. Cost-effective for general turning.",
    brand: "Walter",
    series: "WPP10",
  },

  // ==========================================
  // VBMT — 35° Diamond Positive (Finishing)
  // ==========================================
  {
    id: "vbmt-110304",
    isoCode: "VBMT 110304",
    shape: "V",
    clearance: "C",
    tolerance: "M",
    size: 11,
    thickness: 3.97,
    noseRadius: 0.4,
    chipbreaker: "finishing",
    material: "coated-carbide",
    coating: "tin",
    isoApplicationGroup: "P05-P15",
    recommendedDOC: { min: 0.05, max: 1.0 },
    recommendedFeed: { min: 0.02, max: 0.1 },
    maxDepthOfCut: 1.5,
    maxFeedRate: 0.15,
    notes: "35° sharp point ideal for fine finishing and small grooves.",
    brand: "Sandvik",
    series: "422R",
  },

  // ==========================================
  // WNMG — 80° Trigon (Negative)
  // ==========================================
  {
    id: "wnmg-080408",
    isoCode: "WNMG 080408",
    shape: "W",
    clearance: "N",
    tolerance: "M",
    size: 8,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 4.0 },
    recommendedFeed: { min: 0.08, max: 0.3 },
    maxDepthOfCut: 5.0,
    maxFeedRate: 0.45,
    notes: "Three cutting edges like TNMG but stronger 80° corner.",
    brand: "Kennametal",
    series: "KC5010",
  },

  // ==========================================
  // RCMX — Round Inserts
  // ==========================================
  {
    id: "rcmx-120600",
    isoCode: "RCMX 120600",
    shape: "R",
    clearance: "C",
    tolerance: "M",
    size: 12,
    thickness: 6.0,
    noseRadius: 6.0,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P20-P40",
    recommendedDOC: { min: 0.3, max: 3.0 },
    recommendedFeed: { min: 0.1, max: 0.4 },
    maxDepthOfCut: 6.0,
    maxFeedRate: 0.6,
    notes: "Round insert for contouring and heavy roughing. Infinite approach angles.",
    brand: "Seco",
    series: "TP250",
  },

  // ==========================================
  // Wiper Inserts
  // ==========================================
  {
    id: "cnmg-120408-w",
    isoCode: "CNMG 120408-W",
    shape: "C",
    clearance: "N",
    tolerance: "G",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "wiper",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P25",
    recommendedDOC: { min: 0.15, max: 3.0 },
    recommendedFeed: { min: 0.08, max: 0.5 },
    maxDepthOfCut: 4.0,
    maxFeedRate: 0.6,
    notes: "Wiper geometry — can double feed rate while maintaining surface finish.",
    brand: "Sandvik",
    series: "432R-W",
  },

  // ==========================================
  // Milling Inserts
  // ==========================================
  {
    id: "sphx-120408",
    isoCode: "SPHX 120408",
    shape: "S",
    clearance: "P",
    tolerance: "H",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.5, max: 3.0 },
    recommendedFeed: { min: 0.05, max: 0.2 },
    maxDepthOfCut: 4.0,
    maxFeedRate: 0.3,
    notes: "High-positive milling insert. For general face and edge milling.",
    brand: "Sandvik",
    series: "R245-12",
  },
  {
    id: "sphx-160512",
    isoCode: "SPHX 160512",
    shape: "S",
    clearance: "P",
    tolerance: "H",
    size: 16,
    thickness: 5.56,
    noseRadius: 1.2,
    chipbreaker: "roughing",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P15-P35",
    recommendedDOC: { min: 0.5, max: 5.0 },
    recommendedFeed: { min: 0.08, max: 0.25 },
    maxDepthOfCut: 6.0,
    maxFeedRate: 0.35,
    notes: "Heavy milling insert for roughing. Used in 50mm+ face mills.",
    brand: "Sandvik",
    series: "R245-16",
  },
  {
    id: "octn-050612",
    isoCode: "OCTN 050612",
    shape: "H",
    clearance: "N",
    tolerance: "M" as InsertTolerance,
    size: 5,
    thickness: 6.35,
    noseRadius: 1.2,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "altin",
    isoApplicationGroup: "P15-P35",
    recommendedDOC: { min: 0.5, max: 3.0 },
    recommendedFeed: { min: 0.05, max: 0.2 },
    maxDepthOfCut: 4.0,
    maxFeedRate: 0.3,
    notes: "Octagonal insert with 8 cutting edges. Used in high-feed milling.",
    brand: "Kennametal",
    series: "KCSM40",
  },

  // ==========================================
  // Threading Inserts
  // ==========================================
  {
    id: "16er-ag60",
    isoCode: "16ER AG60",
    shape: "C",
    clearance: "R",
    tolerance: "G",
    size: 16,
    thickness: 4.76,
    noseRadius: 0.15,
    chipbreaker: "finishing",
    material: "coated-carbide",
    coating: "tin",
    isoApplicationGroup: "P10-P20",
    recommendedDOC: { min: 0.02, max: 0.15 },
    recommendedFeed: { min: 0.01, max: 0.05 },
    maxDepthOfCut: 2.0,
    maxFeedRate: 0.1,
    notes: "60° full profile threading insert. For external metric threads.",
    brand: "Iscar",
    series: "THREAD",
  },
  {
    id: "16ir-ag60",
    isoCode: "16IR AG60",
    shape: "C",
    clearance: "R",
    tolerance: "G",
    size: 16,
    thickness: 4.76,
    noseRadius: 0.15,
    chipbreaker: "finishing",
    material: "coated-carbide",
    coating: "tin",
    isoApplicationGroup: "P10-P20",
    recommendedDOC: { min: 0.02, max: 0.15 },
    recommendedFeed: { min: 0.01, max: 0.05 },
    maxDepthOfCut: 2.0,
    maxFeedRate: 0.1,
    notes: "60° full profile threading insert. For internal metric threads.",
    brand: "Iscar",
    series: "THREAD",
  },

  // ==========================================
  // Grooving/Parting Inserts
  // ==========================================
  {
    id: "gfmt-3000-040",
    isoCode: "GFMT 3000-040",
    shape: "W",
    clearance: "F",
    tolerance: "M",
    size: 3,
    thickness: 4.0,
    noseRadius: 0.1,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.1, max: 3.0 },
    recommendedFeed: { min: 0.02, max: 0.15 },
    maxDepthOfCut: 4.0,
    maxFeedRate: 0.2,
    notes: "4mm wide grooving insert. For external grooving and parting.",
    brand: "Iscar",
    series: "PENTA",
  },
  {
    id: "gfmt-3000-060",
    isoCode: "GFMT 3000-060",
    shape: "W",
    clearance: "F",
    tolerance: "M",
    size: 6,
    thickness: 5.0,
    noseRadius: 0.2,
    chipbreaker: "general-purpose",
    material: "coated-carbide",
    coating: "tialn",
    isoApplicationGroup: "P10-P30",
    recommendedDOC: { min: 0.2, max: 5.0 },
    recommendedFeed: { min: 0.05, max: 0.2 },
    maxDepthOfCut: 6.0,
    maxFeedRate: 0.3,
    notes: "6mm wide grooving/parting insert.",
    brand: "Iscar",
    series: "PENTA",
  },

  // ==========================================
  // CBN Inserts — Hard Turning
  // ==========================================
  {
    id: "cbn-dnmg-150408",
    isoCode: "DNMG 150408 CBN",
    shape: "D",
    clearance: "N",
    tolerance: "H",
    size: 15,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "cbn",
    coating: "uncoated",
    isoApplicationGroup: "H10-H20",
    recommendedDOC: { min: 0.03, max: 0.4 },
    recommendedFeed: { min: 0.02, max: 0.12 },
    maxDepthOfCut: 0.6,
    maxFeedRate: 0.18,
    notes: "CBN tipped insert. Finish hard turning of 60+ HRC materials.",
    brand: "Sumitomo",
    series: "BN700",
  },
  {
    id: "cbn-sngn-120408",
    isoCode: "SNGN 120408 CBN",
    shape: "S",
    clearance: "G",
    tolerance: "N",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "cbn",
    coating: "uncoated",
    isoApplicationGroup: "H15-H25",
    recommendedDOC: { min: 0.03, max: 0.3 },
    recommendedFeed: { min: 0.01, max: 0.08 },
    maxDepthOfCut: 0.5,
    maxFeedRate: 0.12,
    notes: "Solid CBN insert for hardened steel and chilled cast iron.",
    brand: "Element Six",
    series: "CBN300",
  },

  // ==========================================
  // PCD Inserts
  // ==========================================
  {
    id: "pcd-ccmt-120408",
    isoCode: "CCMT 120408 PCD",
    shape: "C",
    clearance: "C",
    tolerance: "M",
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "pcd",
    coating: "uncoated",
    isoApplicationGroup: "N05-N15",
    recommendedDOC: { min: 0.05, max: 1.5 },
    recommendedFeed: { min: 0.02, max: 0.12 },
    maxDepthOfCut: 2.0,
    maxFeedRate: 0.18,
    notes: "PCD tipped for high-speed aluminum finishing and non-ferrous materials.",
    brand: "Sumitomo",
    series: "DA2200",
  },

  // ==========================================
  // Ceramic Inserts
  // ==========================================
  {
    id: "cngp-120408-ceramic",
    isoCode: "CNGP 120408 CERAMIC",
    shape: "C",
    clearance: "G",
    tolerance: "M" as InsertTolerance,
    size: 12,
    thickness: 4.76,
    noseRadius: 0.8,
    chipbreaker: "finishing",
    material: "ceramic",
    coating: "uncoated",
    isoApplicationGroup: "K05-K15",
    recommendedDOC: { min: 0.05, max: 2.0 },
    recommendedFeed: { min: 0.03, max: 0.15 },
    maxDepthOfCut: 3.0,
    maxFeedRate: 0.2,
    notes: "Whisker-reinforced ceramic. For high-speed machining of superalloys and cast iron.",
    brand: "Greenleaf",
    series: "WG-300",
  },

  // ==========================================
  // Cermet Inserts
  // ==========================================
  {
    id: "cermet-dcmt-11t304",
    isoCode: "DCMT 11T304 CERMET",
    shape: "D",
    clearance: "C",
    tolerance: "M",
    size: 11,
    thickness: 3.97,
    noseRadius: 0.4,
    chipbreaker: "finishing",
    material: "cermet",
    coating: "uncoated",
    isoApplicationGroup: "P05-P15",
    recommendedDOC: { min: 0.05, max: 1.0 },
    recommendedFeed: { min: 0.02, max: 0.08 },
    maxDepthOfCut: 1.5,
    maxFeedRate: 0.12,
    notes: "Cermet for high-speed finishing of steel. Excellent surface finish and wear resistance.",
    brand: "Kyocera",
    series: "TN150",
  },
];

// ==========================================
// Insert Holders
// ==========================================

const INSERT_HOLDERS: InsertHolderDefinition[] = [
  {
    id: "mclnl-1616h08",
    name: "MCLNL 1616H 08",
    isoCode: "MCLNL-1616H-08",
    shankSize: "16×16",
    length: 100,
    insertSeatSize: 12,
    style: "external",
    maxDepth: 5,
  },
  {
    id: "mclnl-2020k12",
    name: "MCLNL 2020K 12",
    isoCode: "MCLNL-2020K-12",
    shankSize: "20×20",
    length: 125,
    insertSeatSize: 12,
    style: "external",
    maxDepth: 6,
  },
  {
    id: "ddunr-2019c11",
    name: "DDUNR 2019C 11",
    isoCode: "DDUNR-2019C-11",
    shankSize: "20×20",
    length: 125,
    insertSeatSize: 11,
    style: "external",
    maxDepth: 4,
  },
  {
    id: "sclcl-1616h09",
    name: "SCLCL 1616H 09",
    isoCode: "SCLCL-1616H-09",
    shankSize: "16×16",
    length: 100,
    insertSeatSize: 9,
    style: "external",
    maxDepth: 4,
  },
  {
    id: "a16r-sclcl-06",
    name: "A16R-SCLCL 06",
    isoCode: "A16R-SCLCL-06",
    shankSize: "16mm round",
    length: 180,
    insertSeatSize: 6,
    style: "internal",
    maxDepth: 30,
  },
  {
    id: "a20s-sclcl-09",
    name: "A20S-SCLCL 09",
    isoCode: "A20S-SCLCL-09",
    shankSize: "20mm round",
    length: 200,
    insertSeatSize: 9,
    style: "internal",
    maxDepth: 40,
  },
  {
    id: "ghmr-2016-040",
    name: "GHMR 2016-040",
    isoCode: "GHMR-2016-040",
    shankSize: "20×20",
    length: 150,
    insertSeatSize: 4,
    style: "parting",
    maxDepth: 20,
  },
];

export function getInserts(): InsertDefinition[] {
  return [...INSERTS];
}

export function getInsertById(id: string): InsertDefinition | undefined {
  return INSERTS.find((i) => i.id === id);
}

export function getInsertsByShape(shape: InsertShape): InsertDefinition[] {
  return INSERTS.filter((i) => i.shape === shape);
}

export function getInsertsByMaterial(material: string): InsertDefinition[] {
  return INSERTS.filter((i) => i.material === material || i.isoApplicationGroup.includes(material));
}

export function getInsertHolders(): InsertHolderDefinition[] {
  return [...INSERT_HOLDERS];
}

export function getInsertHolderById(id: string): InsertHolderDefinition | undefined {
  return INSERT_HOLDERS.find((h) => h.id === id);
}
